data:
  full_window: 512
  sampling_rate: 125
  test_path: /home/xinchen/ECG/external_data/bidmc_processed/reference_test.pt
  train_path: /home/xinchen/ECG/external_data/bidmc_processed/reference_train.pt
  train_window: 256
device:
  num_workers: 4
  use_amp: false
loss:
  beta: 0.5
  sigma: 1.0
  type: qrs_enhanced
model:
  input_size: 256
  type: ppg2ecg
  use_attention: true
  use_stn: true
output:
  checkpoint_dir: checkpoints/ppg2ecg_bidmc_reference/
  eval_every: 5
  log_dir: logs/ppg2ecg_bidmc/
  save_every: 50
training:
  batch_size: 256
  data_augmentation: true
  epochs: 300
  learning_rate: 0.0001
  optimizer: Adam
  patience: 300
  seed: 2019
  use_scheduler: false
